### ISSUE TITLE
Missed error propagation for on build context creation?

### ISSUE THREAD

**Issue by geropl** [TypeFox/leeway#24]
[This](https://github.com/TypeFox/leeway/blob/b80280bc23e54f066537c4d35b65d5fc8a10eedf/pkg/leeway/build.go#L268) looks like a
```
if err != nil {
  return err
}
```
is missing - alternatively a comment explaining why this is not the case.

@csweichel

**Comment by csweichel** [comment]
Unfortunately the link doesn't seem to include a line number. Where in the file is the issue?

**Comment by AlexTugarev** [comment]
it's L268

https://github.com/TypeFox/leeway/blob/b80280bc23e54f066537c4d35b65d5fc8a10eedf/pkg/leeway/build.go#L268

and ☝️ it looks like the return is missing error case

**Comment by csweichel** [comment]
Indeed. There the error check is missing. I'll fix it later

**Comment by csweichel** [comment]
released as https://github.com/TypeFox/leeway/releases/tag/v0.1.0
