### ISSUE TITLE
[feature-request] Allow to pass multiple (read-only) caches

### ISSUE THREAD

**Issue by geropl** [TypeFox/leeway#31]
This would allow to make use of already built packages in environments where one build (B) "extends" the other (A), but is build in an different environment. A is always build first (and thus it's cache populated), so the subsequent build of B should be able to benefit from that.

**Comment by csweichel** [comment]
Concrete example (@geropl please tell me if this what you had in mind):
In gitpod-io/gitpod we're using two caches: one for master and one for branch builds.
For branch builds, you want to be able to pull from the branch cache AND the master cache. Whereas right now you could only pull from one or the other.

**Comment by geropl** [comment]
#32 introduces `--add-remote-cache <GCP_BUCKET_NAME>` (multiple possible) which serves as additional _download_ (pull) cache.
